### ISSUE TITLE
Ocpp 2.0.1 - Error defining RequestStartTransactionRequest structure

### ISSUE THREAD

**Issue by alexandrepasc** [lorenzodonini/ocpp-go#160] opened 2022-12-18 01:46 UTC
I have been developing an EV Charger simulator using this repository.

When was building the remote handler and testing it against an OCPP connector the remote request start transaction was failing with the error:
```
"FormationViolation","json: cannot unmarshal object into Go struct field RequestStartTransactionRequest.idToken of type types.IdTokenType",null]
error_code=FormationViolation, error_description=json: cannot unmarshal object into Go struct field RequestStartTransactionRequest.idToken of type types.IdTokenType, error_details=None>'
```

I looked at the message sent by the connector, the specifications, the code, and the `RequestStartTransactionRequest` structure in the file `request_start_transaction.go` has an error.

The `IdToken` is defined as `types.IdTokenType` which is a string, but should be an object as the `types.IdToken`.

To have sure that it was not an error from the connector or the work that I'd done I changed the code in some places and after dose changes it worked again.

- ocpp2.0.1/remotecontrol/request_start_transaction.go (line 36)

```
type RequestStartTransactionRequest struct {
	EvseID          *int                   `json:"evseId,omitempty" validate:"omitempty,gt=0"`
	RemoteStartID   int                    `json:"remoteStartId" validate:"gte=0"`
	IDToken         types.IdToken      `json:"idToken" validate:"required"`
	ChargingProfile *types.ChargingProfile `json:"chargingProfile,omitempty"`
	GroupIdToken    types.IdTokenType      `json:"groupIdToken,omitempty" validate:"omitempty,idTokenType"`
}
```

- ocpp2.0.1/remotecontrol/request_start_transaction.go (line 80)
```
func NewRequestStartTransactionRequest(remoteStartID int, IdToken types.IdToken) *RequestStartTransactionRequest {
	return &RequestStartTransactionRequest{RemoteStartID: remoteStartID, IDToken: IdToken}
}
```

- ocpp2.0.1/csms.go (line 434)
```
func (cs *csms) RequestStartTransaction(clientId string, callback func(*remotecontrol.RequestStartTransactionResponse, error), remoteStartID int, IdToken types.IdToken, props ...func(request *remotecontrol.RequestStartTransactionRequest)) error {
	request := remotecontrol.NewRequestStartTransactionRequest(remoteStartID, IdToken)
	for _, fn := range props {
		fn(request)
	}
	genericCallback := func(response ocpp.Response, protoError error) {
		if response != nil {
			callback(response.(*remotecontrol.RequestStartTransactionResponse), protoError)
		} else {
			callback(nil, protoError)
		}
	}
	return cs.SendRequestAsync(clientId, request, genericCallback)
}
```

- ocpp2.0.1/v2.go (line 304)
`RequestStartTransaction(clientId string, callback func(*remotecontrol.RequestStartTransactionResponse, error), remoteStartID int, IdToken types.IdToken, props ...func(request *remotecontrol.RequestStartTransactionRequest)) error`

Not sure that these are the only changes that need to be done to fully correct this, but the simple test that I did was enough .

Hope this will help.

**Comment by lorenzodonini** [comment] 2022-12-24 14:26
Hey there,

thanks a lot for noticing this. It was most likely caused by a naming inconsistency with the `IdToken` enum type and the regular `IdToken`.
The issue was affecting the `RequestStartTransaction` message as well as the `ReserveNow` message. 
The issue is now fixed on the master branch.

**Closed** 2022-12-24 14:25 UTC
Labels: bug, ocpp2.0.1

**Comment by alexandrepasc** [comment] 2023-01-09 16:25
No problem, I'm a QA Engeneer.
